language: node_js

node_js:
   - "stable"
cache:
   directories:
     - node_modules #Cache node_modules for faster builds
before_script:
    - rm -rf node_modules && rm -f package-lock.json
    - npm install
script:
   - npm test #Runs Test
   - npm run build #Creats a production build

deploy:
   provider: heroku
   skip_cleanup: true
   keep-history: true
   api-key:
      secure: $HEROKU_API_KEY
   app: rohan-personal-site
   on: 
      branch: master
